<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>CustomCampaignFramework</AssemblyName>
    <RootNamespace>EndlessMode</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\interop\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MainScriptsAssembly">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\interop\MainScriptsAssembly.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="I2_assembly">
      <HintPath>C:\Steam\steamapps\common\Tape to Tape\BepInEx\interop\I2_assembly.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
